CREATE TABLE IF NOT EXISTS  usuarios(
    id serial PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar NOT NULL  CHECK  (nombre <> ''),
    password varchar NOT NULL  CHECK  (password <> ''),
    apellido varchar NOT NULL  CHECK  (apellido <> ''),
    email varchar NOT NULL UNIQUE  CHECK  (email <> ''),
    fecha date NOT NULL,
    admin boolean NOT NULL
);